### ISSUE TITLE
Linux conversion bug

### ISSUE THREAD

**Issue by Taikakim** [git-moss/ProjectConverter#12]
Conversion from RPP to DAWProject fails. The error seems to be project specific, although everything except an empty project which I have tried generate errors in the same vein.

 I'm on 6.8.0-31-lowlatency #31.1-Ubuntu SMP PREEMPT_DYNAMIC, and have an I7 6700.

Index 4 out of bounds for length 4
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at java.base/java.util.Objects.checkIndex(Unknown Source)
at java.base/java.util.ArrayList.get(Unknown Source)
at de.mossgrabers.projectconverter.format.reaper.ReaperSourceFormat.convertDevice(ReaperSourceFormat.java:937)
at de.mossgrabers.projectconverter.format.reaper.ReaperSourceFormat.convertDevices(ReaperSourceFormat.java:837)
at de.mossgrabers.projectconverter.format.reaper.ReaperSourceFormat.convertMaster(ReaperSourceFormat.java:480)
at de.mossgrabers.projectconverter.format.reaper.ReaperSourceFormat.read(ReaperSourceFormat.java:203)
at de.mossgrabers.projectconverter.core.ConversionTask.call(ConversionTask.java:63)
at de.mossgrabers.projectconverter.core.ConversionTask.call(ConversionTask.java:23)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1401)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Done.

**Comment by Taikakim** [comment]
Woops my bad, the songs were in very old versions on Reaper, re-saving them in v7 first seems to help.
