### ISSUE TITLE
Can't convert from Bitwig 3.0 to Reaper

### ISSUE THREAD

**Issue by Dharkf** [git-moss/ProjectConverter#8]
Hi, I keep getting this error message from any project i try to convert from Bitwig.

Parsing source project: ...\TECLAS FALSA PROMESA.bwproject
entry
java.lang.NullPointerException: entry

at java.base/java.util.Objects.requireNonNull(Unknown Source)

at java.base/java.util.zip.ZipFile.getInputStream(Unknown Source)

at com.bitwig.dawproject.DawProject.loadMetadata(DawProject.java:224)

at de.mossgrabers.projectconverter.core.DawProjectContainer.<init>(DawProjectContainer.java:57)

at de.mossgrabers.projectconverter.format.dawproject.DawProjectSourceFormat.read(DawProjectSourceFormat.java:67)

at de.mossgrabers.projectconverter.core.ConversionTask.call(ConversionTask.java:63)

at de.mossgrabers.projectconverter.core.ConversionTask.call(ConversionTask.java:23)

at javafx.concurrent.Task$TaskCallable.call(Task.java:1399)

at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.base/java.lang.Thread.run(Unknown Source)

**Comment by git-moss** [comment]
There is a misunderstanding. This tool does not convert Bitwig project files but DAWproject files. Bitwig can read/write this format since version 5. Watch this: https://www.youtube.com/watch?v=q91u5VqK61c
